name: "Build"

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Download goboscript compiler
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: IMG-F/goboscript
          file: goboscript-x86_64-unknown-linux-gnu
          target: goboscript-compiler
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make compiler executable
        run: chmod +x goboscript-compiler

      - name: Build project
        run: |
          ./goboscript-compiler build

      - name: Create timestamp
        id: create_timestamp
        run: echo "timestamp=$(date '+%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Upload sb3 to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.sb3"
          tag_name: ${{ github.event_name != 'release' && format('snapshot-{0}', steps.create_timestamp.outputs.timestamp) || github.event.release.tag_name }}
          body: ${{ github.event_name != 'release' && github.event.head_commit.message || github.event.release.body }}
          prerelease: ${{ github.event_name != 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: CCW Deploy Action
        uses: IMG-F/deploy-to-ccw@v1.0.2
        with:
          oid: "691477bc1d82a725986fb672"
          sb3FilePath: "./KanonBloss.sb3"
          coverFilePath: "./.deploy/cover.png"
          title: "github action 自动化发布测试"
          description: >-
            如你所见, 这是一个由 github action 自动发布的作品

            该作品使用 [goboscript](https://github.com/aspizu/goboscript/) 制作, 
            通过 github action 自动化构建和发布, 只需在 github 上发布 release 即可, 
            实现持续集成和持续交付(CI/CD)
            
            详见 [ming-sc/KanonBloss](https://github.com/ming-sc/KanonBloss)
          operatingInstruction: ""
          releaseDescription: ${{ github.event_name != 'release' && github.event.head_commit.message || github.event.release.body }}
          customVersion: "1.0.0"
          publishedFeedSwitch: "false"
          token: ${{ secrets.token }}
          userId: ${{ secrets.userId }}
